export const serviceIconCategoryOrder = [
  'system',
  'files',
  'media',
  'development',
  'network',
  'security',
  'communication',
] as const

export type ServiceIconCategoryKey = (typeof serviceIconCategoryOrder)[number]

export const serviceIconCategoryAliases: Record<ServiceIconCategoryKey, readonly string[]> = {
  system: ['系统', '应用', '设备', '桌面'],
  files: ['文件', '文档', '目录', '存储'],
  media: ['媒体', '图片', '视频', '音频'],
  development: ['开发', '代码', '终端', '数据库'],
  network: ['网络', '网站', '浏览器', '云'],
  security: ['安全', '权限', '密码', '密钥'],
  communication: ['消息', '邮件', '通知', '日历'],
}

export const serviceIconTokenCategories: Record<string, readonly ServiceIconCategoryKey[]> = {
  album: ['media'],
  app: ['system'],
  archive: ['files'],
  audio: ['media'],
  bell: ['communication'],
  bookmark: ['files'],
  book: ['files'],
  bot: ['development'],
  brain: ['development'],
  briefcase: ['system'],
  bug: ['development'],
  calendar: ['communication'],
  camera: ['media'],
  cloud: ['network'],
  code: ['development'],
  cog: ['system'],
  database: ['development', 'files'],
  download: ['files', 'network'],
  drive: ['files'],
  file: ['files'],
  files: ['files'],
  folder: ['files'],
  gallery: ['media'],
  git: ['development'],
  globe: ['network'],
  hard: ['files'],
  house: ['system'],
  image: ['media'],
  images: ['media'],
  key: ['security'],
  laptop: ['system'],
  link: ['network'],
  lock: ['security'],
  mail: ['communication'],
  message: ['communication'],
  messages: ['communication'],
  mic: ['media'],
  monitor: ['system'],
  music: ['media'],
  network: ['network'],
  package: ['system'],
  phone: ['system'],
  play: ['media'],
  printer: ['system'],
  rss: ['communication', 'network'],
  search: ['system'],
  server: ['development', 'network'],
  settings: ['system'],
  shield: ['security'],
  smartphone: ['system'],
  tablet: ['system'],
  tag: ['files'],
  terminal: ['development'],
  text: ['files'],
  upload: ['files', 'network'],
  user: ['communication'],
  users: ['communication'],
  video: ['media'],
  wifi: ['network'],
  window: ['system'],
  wrench: ['system'],
}

export const serviceIconTokenAliases: Record<string, readonly string[]> = {
  album: ['相册', '专辑'],
  app: ['应用'],
  archive: ['归档'],
  audio: ['音频', '声音'],
  bell: ['通知', '提醒'],
  bookmark: ['书签', '收藏'],
  book: ['书籍', '文档'],
  bot: ['机器人', 'AI'],
  brain: ['智能', 'AI'],
  briefcase: ['办公', '工作'],
  bug: ['调试', '缺陷'],
  calendar: ['日历', '日程'],
  camera: ['相机', '拍照'],
  cloud: ['云', '云端'],
  code: ['代码', '开发'],
  cog: ['设置', '齿轮'],
  database: ['数据库', '存储'],
  download: ['下载'],
  drive: ['磁盘', '硬盘'],
  file: ['文件', '文档'],
  files: ['文件', '文档'],
  folder: ['文件夹', '目录'],
  gallery: ['相册', '图库'],
  git: ['代码', 'Git'],
  globe: ['网络', '互联网', '全球'],
  hard: ['硬盘', '存储'],
  heart: ['喜欢', '收藏'],
  house: ['首页', '主页'],
  image: ['图片', '图像', '照片'],
  images: ['图片', '相册', '图库'],
  key: ['钥匙', '密钥', '密码'],
  laptop: ['笔记本', '电脑'],
  link: ['链接', '外链'],
  lock: ['锁', '安全', '密码'],
  mail: ['邮件', '邮箱'],
  message: ['消息', '聊天'],
  messages: ['消息', '聊天'],
  mic: ['麦克风', '录音'],
  monitor: ['显示器', '屏幕'],
  music: ['音乐'],
  network: ['网络'],
  package: ['包裹', '应用'],
  phone: ['电话'],
  play: ['播放'],
  printer: ['打印机'],
  rss: ['订阅', 'RSS'],
  search: ['搜索', '查找'],
  server: ['服务器', '服务端'],
  settings: ['设置', '配置'],
  shield: ['安全', '防护'],
  smartphone: ['手机'],
  star: ['星标', '收藏'],
  tablet: ['平板'],
  tag: ['标签'],
  terminal: ['终端', '命令行'],
  text: ['文本', '文档'],
  upload: ['上传'],
  user: ['用户', '账号', '个人'],
  users: ['用户', '团队', '成员'],
  video: ['视频'],
  wifi: ['无线', 'WiFi'],
  window: ['窗口'],
  wrench: ['工具', '维修'],
}

export const serviceIconManualAliases: Record<string, readonly string[]> = {
  'app-window': ['应用窗口', '浏览器'],
  'app-window-mac': ['应用窗口', '浏览器', '桌面应用'],
  bookmark: ['书签', '收藏'],
  camera: ['相机', '拍照'],
  cloud: ['云盘', '云服务'],
  database: ['数据库', 'DB'],
  folder: ['文件夹', '目录'],
  'folder-open': ['文件夹', '打开文件夹', '打开目录'],
  globe: ['网络', '互联网', '网站'],
  'hard-drive': ['硬盘', '磁盘', '存储', 'NAS'],
  house: ['首页', '主页'],
  image: ['图片', '照片', '相册'],
  images: ['图片', '相册', '图库'],
  'key-round': ['密钥', '钥匙', '密码'],
  lock: ['锁', '密码', '安全'],
  mail: ['邮件', '邮箱'],
  'message-square': ['消息', '聊天', '对话'],
  monitor: ['显示器', '屏幕', '电脑'],
  rss: ['订阅', 'RSS'],
  search: ['搜索', '查找'],
  server: ['服务器', '服务端'],
  settings: ['设置', '配置', '齿轮'],
  'settings-2': ['设置', '配置', '齿轮'],
  shield: ['安全', '防护'],
  'shield-check': ['安全', '验证', '校验'],
  smartphone: ['手机', '移动端'],
  'square-terminal': ['终端', '命令行', '控制台'],
  terminal: ['终端', '命令行', '控制台'],
  wifi: ['无线网络', 'WiFi'],
}

export const serviceIconManualCategories: Record<string, readonly ServiceIconCategoryKey[]> = {
  'app-window': ['system', 'network'],
  'app-window-mac': ['system'],
  bookmark: ['files'],
  camera: ['media'],
  cloud: ['network', 'files'],
  database: ['development', 'files'],
  folder: ['files'],
  'folder-open': ['files'],
  globe: ['network'],
  'hard-drive': ['files'],
  house: ['system'],
  image: ['media'],
  images: ['media'],
  'key-round': ['security'],
  lock: ['security'],
  mail: ['communication'],
  'message-square': ['communication'],
  monitor: ['system'],
  rss: ['communication', 'network'],
  search: ['system'],
  server: ['development', 'network'],
  settings: ['system'],
  'settings-2': ['system'],
  shield: ['security'],
  'shield-check': ['security'],
  smartphone: ['system'],
  'square-terminal': ['development'],
  terminal: ['development'],
  wifi: ['network'],
}
